#!/usr/bin/env python3
"""
build_index.py
===============

Walk docs/vocabulary/ · build docs/vocabulary/index.md.

The index is the human-readable catalog · grouped by category subdir,
alphabetical within each category, markdown-table format. Columns:

    | Term | Slug | Category | 1-line Definition |

The 1-line definition is extracted from the Street Definition section
of each term file. If absent, the first non-blank line under the H1 is
used as a fallback.

Usage:
    python scripts/build_index.py
    python scripts/build_index.py --vocab-dir docs/vocabulary --out docs/vocabulary/index.md
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

import click

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_VOCAB_DIR = REPO_ROOT / "docs" / "vocabulary"
DEFAULT_OUT = DEFAULT_VOCAB_DIR / "index.md"

H1_RE = re.compile(r"^#\s+(.+?)\s*$")
H2_RE = re.compile(r"^##\s+(.+?)\s*$")
SLUG_NORMALIZE = re.compile(r"[^a-z0-9]+")


@dataclass
class TermRow:
    term: str
    slug: str
    category: str
    one_line: str
    rel_path: str


def _slugify(term: str) -> str:
    s = SLUG_NORMALIZE.sub("-", term.lower()).strip("-")
    return s or "untitled"


def _extract_one_line(body: str) -> str:
    """Pull the first sentence-ish line under the Street Definition H2.
    Fallback: first non-blank line of the file body.
    """
    lines = body.splitlines()
    in_street = False
    fallback = ""
    for raw in lines:
        line = raw.strip()
        if not fallback and line and not line.startswith("#") and not line.startswith(">"):
            fallback = line
        m = H2_RE.match(raw)
        if m:
            if in_street:
                break
            if m.group(1).strip().lower().startswith("street definition"):
                in_street = True
                continue
        if in_street and line and not line.startswith(">") and not line.startswith("#"):
            # strip markdown emphasis around the leading phrase for compactness
            clean = re.sub(r"\*+", "", line)
            return _truncate(clean, 140)
    return _truncate(fallback, 140) if fallback else "(no definition extracted)"


def _truncate(text: str, n: int) -> str:
    return text if len(text) <= n else text[: n - 1].rstrip() + "…"


def _read_term(path: Path, vocab_dir: Path) -> TermRow | None:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return None
    term_name = path.stem.replace("-", " ").title()
    for line in text.splitlines():
        m = H1_RE.match(line)
        if m:
            term_name = m.group(1).strip()
            break
    category = path.relative_to(vocab_dir).parts[0] if path.parent != vocab_dir else "uncategorized"
    one_line = _extract_one_line(text)
    return TermRow(
        term=term_name,
        slug=_slugify(term_name),
        category=category,
        one_line=one_line,
        rel_path=str(path.relative_to(REPO_ROOT)),
    )


def _render_index(rows: list[TermRow]) -> str:
    by_cat: dict[str, list[TermRow]] = {}
    for row in rows:
        by_cat.setdefault(row.category, []).append(row)

    parts: list[str] = []
    parts.append("# Defend-A-Pedia · Vocabulary Index")
    parts.append("")
    parts.append(
        f"> Auto-generated by `scripts/build_index.py` on "
        f"{datetime.now(timezone.utc).isoformat(timespec='seconds')}. "
        f"Do not edit by hand."
    )
    parts.append("")
    parts.append(f"Categories: **{len(by_cat)}** · Terms: **{len(rows)}**")
    parts.append("")

    parts.append("## Categories")
    parts.append("")
    for cat in sorted(by_cat):
        parts.append(f"- [{cat}](#{cat.replace('_', '-')}) · {len(by_cat[cat])} terms")
    parts.append("")

    for cat in sorted(by_cat):
        parts.append(f"## {cat}")
        parts.append("")
        parts.append("| Term | Slug | Category | Definition |")
        parts.append("|---|---|---|---|")
        for row in sorted(by_cat[cat], key=lambda r: r.term.lower()):
            term_link = f"[{row.term}](../../{row.rel_path})"
            one_line = row.one_line.replace("|", "\\|")
            parts.append(f"| {term_link} | `{row.slug}` | `{row.category}` | {one_line} |")
        parts.append("")

    parts.append("---")
    parts.append("")
    parts.append("🐝 *The language lives in the blocks.*")
    parts.append("")
    return "\n".join(parts)


@click.command()
@click.option(
    "--vocab-dir",
    type=click.Path(exists=True, file_okay=False, path_type=Path),
    default=DEFAULT_VOCAB_DIR,
    show_default=True,
)
@click.option(
    "--out",
    type=click.Path(dir_okay=False, path_type=Path),
    default=DEFAULT_OUT,
    show_default=True,
)
def main(vocab_dir: Path, out: Path) -> None:
    rows: list[TermRow] = []
    for path in sorted(vocab_dir.rglob("*.md")):
        if path.name.lower() in {"readme.md", "index.md", "term_matrix.md"}:
            continue
        row = _read_term(path, vocab_dir)
        if row is not None:
            rows.append(row)

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_render_index(rows), encoding="utf-8")
    click.echo(f"[build_index] wrote {len(rows)} term rows → {out.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
