#!/usr/bin/env python3
"""
generate_term_matrix.py
========================

Build the cross-reference matrix of vocabulary terms.

For every term file:
    · parse the Related Terms section
    · normalize every link target to a slug
    · record `links_to`  · the slugs this term points OUT to
    · record `linked_from` · computed in a second pass · which terms point at it

Outputs:
    assets/diagrams/term_matrix.json   · machine-readable matrix
    docs/vocabulary/term_matrix.md     · human-readable summary table

Usage:
    python scripts/generate_term_matrix.py
    python scripts/generate_term_matrix.py --vocab-dir docs/vocabulary
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path

import click

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_VOCAB_DIR = REPO_ROOT / "docs" / "vocabulary"
DEFAULT_JSON_OUT = REPO_ROOT / "assets" / "diagrams" / "term_matrix.json"
DEFAULT_MD_OUT = DEFAULT_VOCAB_DIR / "term_matrix.md"

H1_RE = re.compile(r"^#\s+(.+?)\s*$")
H2_RE = re.compile(r"^##\s+(.+?)\s*$")
LINK_RE = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
SLUG_NORMALIZE = re.compile(r"[^a-z0-9]+")


def _slugify(text: str) -> str:
    return SLUG_NORMALIZE.sub("-", text.lower()).strip("-") or "untitled"


def _read_title_and_related(text: str) -> tuple[str, list[str]]:
    title = ""
    related_lines: list[str] = []
    in_related = False
    for raw in text.splitlines():
        if not title:
            m1 = H1_RE.match(raw)
            if m1:
                title = m1.group(1).strip()
        m2 = H2_RE.match(raw)
        if m2:
            heading = m2.group(1).strip().lower()
            in_related = heading.startswith("related terms")
            continue
        if in_related:
            related_lines.append(raw)
    related_blob = "\n".join(related_lines)
    slugs: list[str] = []
    seen: set[str] = set()
    for _label, target in LINK_RE.findall(related_blob):
        slug = _slugify(Path(target).stem)
        if slug and slug not in seen:
            seen.add(slug)
            slugs.append(slug)
    return title, slugs


@click.command()
@click.option(
    "--vocab-dir",
    type=click.Path(exists=True, file_okay=False, path_type=Path),
    default=DEFAULT_VOCAB_DIR,
    show_default=True,
)
@click.option(
    "--json-out",
    type=click.Path(dir_okay=False, path_type=Path),
    default=DEFAULT_JSON_OUT,
    show_default=True,
)
@click.option(
    "--md-out",
    type=click.Path(dir_okay=False, path_type=Path),
    default=DEFAULT_MD_OUT,
    show_default=True,
)
def main(vocab_dir: Path, json_out: Path, md_out: Path) -> None:
    matrix: dict[str, dict] = {}
    for path in sorted(vocab_dir.rglob("*.md")):
        name = path.name.lower()
        if name in {"readme.md", "index.md", "term_matrix.md"}:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            continue
        title, links_to = _read_title_and_related(text)
        slug = _slugify(title) if title else _slugify(path.stem)
        category = (
            path.relative_to(vocab_dir).parts[0]
            if path.parent != vocab_dir
            else "uncategorized"
        )
        matrix[slug] = {
            "term": title or path.stem,
            "slug": slug,
            "category": category,
            "source": str(path.relative_to(REPO_ROOT)),
            "links_to": links_to,
            "linked_from": [],
        }

    # Second pass · invert
    for slug, entry in matrix.items():
        for target_slug in entry["links_to"]:
            if target_slug in matrix and slug not in matrix[target_slug]["linked_from"]:
                matrix[target_slug]["linked_from"].append(slug)

    json_out.parent.mkdir(parents=True, exist_ok=True)
    json_payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "term_count": len(matrix),
        "edge_count": sum(len(e["links_to"]) for e in matrix.values()),
        "terms": matrix,
    }
    json_out.write_text(json.dumps(json_payload, indent=2, sort_keys=True), encoding="utf-8")

    # Markdown summary
    md_lines: list[str] = []
    md_lines.append("# Vocabulary Term Matrix")
    md_lines.append("")
    md_lines.append(
        f"> Auto-generated by `scripts/generate_term_matrix.py` on "
        f"{json_payload['generated_at']}. Do not edit by hand."
    )
    md_lines.append("")
    md_lines.append(
        f"**{json_payload['term_count']}** terms · "
        f"**{json_payload['edge_count']}** outbound links · "
        f"machine-readable: [`{json_out.relative_to(REPO_ROOT)}`]"
        f"(../../{json_out.relative_to(REPO_ROOT)})"
    )
    md_lines.append("")
    md_lines.append("| Slug | Category | Links to | Linked from |")
    md_lines.append("|---|---|---:|---:|")
    for slug in sorted(matrix):
        entry = matrix[slug]
        md_lines.append(
            f"| `{slug}` | `{entry['category']}` | "
            f"{len(entry['links_to'])} | {len(entry['linked_from'])} |"
        )
    md_lines.append("")
    md_out.parent.mkdir(parents=True, exist_ok=True)
    md_out.write_text("\n".join(md_lines), encoding="utf-8")

    click.echo(
        f"[generate_term_matrix] {json_payload['term_count']} terms · "
        f"{json_payload['edge_count']} edges · "
        f"json → {json_out.relative_to(REPO_ROOT)} · md → {md_out.relative_to(REPO_ROOT)}"
    )


if __name__ == "__main__":
    main()
