#!/usr/bin/env python3
"""
generate_docs_site.py
======================

PLACEHOLDER · the actual docs site build is deferred. Today this script just
emits docs/site_build_notes.md describing what the future docs site would do
so SH6 and any future contributor knows the contract.

Usage:
    python scripts/generate_docs_site.py
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import click

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = REPO_ROOT / "docs" / "site_build_notes.md"

NOTES = """# Defend-A-Pedia · Docs Site Build Notes

> Auto-generated by `scripts/generate_docs_site.py` on {timestamp}.
> The full docs site is deferred. This file describes the intended contract so
> any future builder picks up exactly where SH2 left off.

## Intent

Render the entire `docs/` tree into a static site that operators · jr brokers ·
clients · and AI fine-tuners can browse without a Markdown reader. The site is
NOT a marketing surface. It is the operator playbook · the schema bible · the
training-pair index.

## Surfaces

| Path | Source | Notes |
|---|---|---|
| `/` | `README.md` | repository front door |
| `/doctrine/` | `docs/doctrine/*.md` | 16 foundational docs · read in order |
| `/vocabulary/` | `docs/vocabulary/**/*.md` | per-term pages · grouped by category |
| `/vocabulary/index` | `docs/vocabulary/index.md` | generated by `build_index.py` |
| `/vocabulary/matrix` | `docs/vocabulary/term_matrix.md` | generated by `generate_term_matrix.py` |
| `/schemas/` | `docs/schemas/*.schema.json` | rendered with field tables |
| `/playbooks/` | `docs/playbooks/*.md` | jr broker · sr broker · Tribunal · SwarmFixer |
| `/ui_dials/` | `docs/ui_dials/*.md` | dial specs |
| `/examples/` | `docs/examples/*.md` | canonical term + receipt examples |
| `/data/` | `data/*.jsonl` (download links) | training-ready corpora |

## Build inputs

1. `scripts/build_index.py` runs first · regenerates the index
2. `scripts/generate_term_matrix.py` runs second · regenerates the matrix
3. `scripts/export_backend_map.py` runs third · refreshes the field map
4. `scripts/export_client_dictionary.py` runs fourth · refreshes client copy
5. `scripts/validate_*.py` MUST pass before the site emits

## Renderer (when built)

- Static site generator (MkDocs Material is the leading candidate · operator-readable)
- AI-friendly: `llms.txt` at site root · category-level `llms-full.txt` per category
- Each term page emits structured data (Schema.org `DefinedTerm`) so Perplexity ·
  ClaudeBot · GPTBot · PerplexityBot · Googlebot pick up the canonical definition
- Linkcheck CI: every Related Terms link must resolve (mirrors `test_cross_reference_links.py`)

## Out of scope for today

- Theme / branding (handled by the defendableos.com pipeline once vocabulary lands)
- Search index (defer to MkDocs default or Algolia DocSearch)
- Comments / annotations (this is a constitution · not a forum)

🐝 *The language lives in the blocks · the site just makes the blocks readable.*
"""


@click.command()
@click.option(
    "--out",
    type=click.Path(dir_okay=False, path_type=Path),
    default=DEFAULT_OUT,
    show_default=True,
)
def main(out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        NOTES.format(timestamp=datetime.now(timezone.utc).isoformat(timespec="seconds")),
        encoding="utf-8",
    )
    click.echo(f"[generate_docs_site] wrote placeholder notes → {out.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
